Homework 2
================
Chloe Chah

``` r
library(tidyverse)
```

    ## ── Attaching packages ───────────────────────────────────── tidyverse 1.3.0 ──

    ## ✓ ggplot2 3.3.2     ✓ purrr   0.3.4
    ## ✓ tibble  3.0.3     ✓ dplyr   1.0.2
    ## ✓ tidyr   1.1.2     ✓ stringr 1.4.0
    ## ✓ readr   1.3.1     ✓ forcats 0.5.0

    ## ── Conflicts ──────────────────────────────────────── tidyverse_conflicts() ──
    ## x dplyr::filter() masks stats::filter()
    ## x dplyr::lag()    masks stats::lag()

``` r
library(readxl)
```

## Problem 1

#### Read the Mr.Trashwheel dataset.

``` r
trashwheel_df = 
  read_xlsx(
    "./data/Trash-Wheel-Collection-Totals-8-6-19.xlsx",
    sheet = "Mr. Trash Wheel",
    range = cell_cols("A:N")) %>% 
  janitor::clean_names() %>%
  drop_na(dumpster) %>%
  mutate(
    sports_balls = round(sports_balls), 
    sports_balls = as.integer(sports_balls)
  )
```

#### Read precipitation data\!

``` r
  precip_2018 = 
   read_excel(
     "./data/Trash-Wheel-Collection-Totals-8-6-19.xlsx", 
     sheet = "2018 Precipitation", 
     skip = 1
   )%>% 
  janitor::clean_names() %>%
  drop_na (month) %>%
  mutate(year = 2018) %>%
  relocate(year)

precip_2017 = 
  read_excel(
     "./data/Trash-Wheel-Collection-Totals-8-6-19.xlsx", 
     sheet = "2017 Precipitation", 
     skip = 1
   ) %>% 
  janitor::clean_names() %>%
  drop_na(month) %>%
  mutate(year = 2017) %>%
  relocate(year)
```

#### Now combine annual precipitation.

``` r
  month_df = 
    tibble(
      month = 1:12, 
      month_name = month.name
    )
  
  precip_df = 
    bind_rows(precip_2018, precip_2017)
  
  left_join(precip_df, month_df, by = "month")
```

    ## # A tibble: 24 x 4
    ##     year month total month_name
    ##    <dbl> <dbl> <dbl> <chr>     
    ##  1  2018     1  0.94 January   
    ##  2  2018     2  4.8  February  
    ##  3  2018     3  2.69 March     
    ##  4  2018     4  4.69 April     
    ##  5  2018     5  9.27 May       
    ##  6  2018     6  4.77 June      
    ##  7  2018     7 10.2  July      
    ##  8  2018     8  6.45 August    
    ##  9  2018     9 10.5  September 
    ## 10  2018    10  2.12 October   
    ## # … with 14 more rows

This dataset contains information from the Mr. Trashwheel trash
collector in Baltimore, Maryland. As trash enters the inner harbor, the
trashwheel collects that trash and stores it in a dumpster. The dataset
contains information on year, month, and trash collected, including some
specific kinds of trash. There are a total of 344 rows in our final
dataset. Additional data sheets include monthly precipitation data.

## Problem 2

#### Read in csv file, clean variable names, convert entry variable

``` r
   transit_df = read_csv(
     "./data/NYC_Transit_Subway_Entrance_And_Exit_Data.csv") %>%
    janitor::clean_names() %>%
    select(line:entry, vending, ada) %>%
    mutate(entry = ifelse(entry == "YES", "True", "False"))
```

    ## Parsed with column specification:
    ## cols(
    ##   .default = col_character(),
    ##   `Station Latitude` = col_double(),
    ##   `Station Longitude` = col_double(),
    ##   Route8 = col_double(),
    ##   Route9 = col_double(),
    ##   Route10 = col_double(),
    ##   Route11 = col_double(),
    ##   ADA = col_logical(),
    ##   `Free Crossover` = col_logical(),
    ##   `Entrance Latitude` = col_double(),
    ##   `Entrance Longitude` = col_double()
    ## )

    ## See spec(...) for full column specifications.

#### Description of the NYC Transit dataset

The dataset contains information related to each entrance and exit for
each subway station in New York City. It contains the following
variables: ada, entrance\_type, entry, line, route1, route10, route11,
route2, route3, route4, route5, route6, route7, route8, route9,
station\_latitude, station\_longitude, station\_name, vending. The
dataset has 1868 rows and 19 columns.

In terms of the data cleaning steps, I first read the csv file into R,
used the clean\_names() function to clean the variable names. Then I
used the select function to retain only the desired variables. I’ve also
converted the entry variable from a character variable to a logical
variable.

This dataset is not yet tidy because there are redundant columns that
seem to describe the same thing.

#### Counting the number of distinct stations

``` r
  distinct(transit_df, line, station_name, .keep_all = TRUE) %>%
  nrow()
```

    ## [1] 465

There are a total of 465 unique stations.

#### How many stations are ADA compliant?

``` r
  distinct(transit_df, line, station_name, .keep_all = TRUE) %>% 
  filter(ada == TRUE) %>%
  nrow() 
```

    ## [1] 84

There a total of 84 stations that are ADA compliant.

#### What proportion of station entrances / exits without vending allow entrance?

``` r
  group_by(transit_df, vending) %>%
  summarise(vending = n())
```

    ## `summarise()` ungrouping output (override with `.groups` argument)

    ## # A tibble: 2 x 1
    ##   vending
    ##     <int>
    ## 1     183
    ## 2    1685

``` r
  group_by(transit_df, vending, entry) %>%
  summarise(vending = n())
```

    ## `summarise()` regrouping output by 'vending' (override with `.groups` argument)

    ## # A tibble: 4 x 2
    ## # Groups:   vending [4]
    ##   vending entry
    ##     <int> <chr>
    ## 1     114 False
    ## 2      69 True 
    ## 3       1 False
    ## 4    1684 True

``` r
  69/183
```

    ## [1] 0.3770492

There are a total of 183 station entrances/exits without vending. Of
those, 69 entrances/exits allow entry. So 37.704918% of the station
entrances/exits without vending allow entrance.

#### Reformating data so that route number and route name are distinct variables

## Problem 3

#### Reading in & cleaning data; breaking up mon variable; replacing month number with month name; deleting day variable;

``` r
pols_df = read_csv(
    "./data/pols-month.csv") %>%
    janitor::clean_names() %>%
    separate(mon, sep = "-", into = c("year", "month", "day"))
```

    ## Parsed with column specification:
    ## cols(
    ##   mon = col_date(format = ""),
    ##   prez_gop = col_double(),
    ##   gov_gop = col_double(),
    ##   sen_gop = col_double(),
    ##   rep_gop = col_double(),
    ##   prez_dem = col_double(),
    ##   gov_dem = col_double(),
    ##   sen_dem = col_double(),
    ##   rep_dem = col_double()
    ## )

``` r
pols_df$month = as.numeric(pols_df$month)

month_df = 
    tibble(
        month = 1:12,
        month_name = month.name
    )

pols_df =
    left_join(pols_df, month_df, by = "month") %>%
    relocate(month_name, .after = "month") 

pols_df = subset(pols_df, select = -day)
```
